apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-nexus
spec:
  destination:
    name: ''
    namespace: rozdzielnia
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/acme-nexus
    repoURL: 'https://github.com/mmartofel/gitops-opentlc'
    targetRevision: HEAD
  project: acme-frontend-microservice-postgres
