apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nexus
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: nexus-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi